// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Pool, Gym, Parking",
                            CreatedDate = new DateTime(2024, 11, 28, 11, 52, 25, 536, DateTimeKind.Local).AddTicks(4059),
                            Details = "A spacious luxury apartment with modern amenities.",
                            ImageUrl = "https://example.com/luxury-apartment.jpg",
                            Name = "Luxury Apartment",
                            Occupancy = 4,
                            Rate = 1500.0,
                            Sqft = 1200,
                            UpdatedDate = new DateTime(2024, 11, 28, 11, 52, 25, 540, DateTimeKind.Local).AddTicks(4565)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Wi-Fi, Coffee Maker",
                            CreatedDate = new DateTime(2024, 11, 28, 11, 52, 25, 540, DateTimeKind.Local).AddTicks(4901),
                            Details = "A small, cozy studio apartment in the city center.",
                            ImageUrl = "https://example.com/cozy-studio.jpg",
                            Name = "Cozy Studio",
                            Occupancy = 2,
                            Rate = 800.0,
                            Sqft = 450,
                            UpdatedDate = new DateTime(2024, 11, 28, 11, 52, 25, 540, DateTimeKind.Local).AddTicks(4904)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
